# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27954001f24a7ffa08a29b4ff55441c7e1d15c23e31c3c6ebb0e50d69f029132c6b584496275d9723f8246573cf217d9e874ca8b597c9fa6cf16cb4f52015011

test:
  secret_key_base: c16f24d68eb9417dd20813e603657b45cd00081bdef552d896957ef9e6d334fb7ce829d4063578fc4f142b3e5e3231ecf2a3b0a045600c0bfcb5f094da517172

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
